### ISSUE TITLE
How to install a stand-alone parcels package?

### ISSUE THREAD

**Issue by willirath** [OceanParcels/parcels#225]
## Why?

At Geomar, we have a central Jupyter Hub allowing for running remote kernels on virtually all of our analysis machines. The remote backends rely on Conda environments. Ideally, we'd be able to include a parcels environment satisfying the `requirements.txt` and adding a parcels package.

The basic logic behind our backend setup follows a very nice blog post by @rabernat: https://medium.com/@rabernat/custom-conda-environments-for-data-science-on-hpc-clusters-32d58c63aa95

The following env file (largely based on parcel's `requirements.txt`) seems to get close to a working parcels setup:

```yml
name: py2_parcels
channels:
  - https://conda.anaconda.org/conda-forge
  - https://repo.continuum.io/pkgs/free
dependencies:
  - python=2.7
  - cachetools>=1.0.0
  - cgen
  - enum34
  - flake8>=2.1.0
  - jupyter
  - matplotlib
  - netcdf4>=1.1.9
  - numpy>=1.9.1
  - progressbar2
  - py>=1.4.27
  - pymbolic
  - python-dateutil
  - scipy>=0.16.0
  - six>=1.10.0
  - xarray>=0.5.1
  - pip:
      - pytest-ipynb
      - pytest>=2.7.0
      - "git+https://github.com/OceanParcels/parcels.git@v0.9"
```

## Problem

Running the [parcels tutorial](http://nbviewer.jupyter.org/github/OceanParcels/parcels/blob/master/examples/parcels_tutorial.ipynb) with essentially the following steps works only partially:

```bash
source activate py2_parcels
git clone https://github.com/OceanParcels/parcels.git parcels
cd parcels
git fetch --tags
git checkout v0.9
python parcels/scripts/pull_data.py
jupyter notebook
```

I do, however, run into problems with `gcc` being unable to compile, because of a missing `includes/parcels.h`. Import statements seem to use the installed version (as intended) while only the tutorial itself and the `pull_data.py` from the cloned version are used.

## Going forward

I'd be fine with providing a PR for a decent `setup.py` and / or documentation. Before being able to do so, I think, I'll have to understand how a user is supposed to work with parcels:
- Keeping a full copy of the repo for each experiment?
- Or having a central installation?

(Probably related to #104)
(cc: @sruehs)

**Comment by rabernat** [comment]
Probably best to package parcels via conda forge.

**Comment by willirath** [comment]
Adding a conda-forge package would be ideal. This would also help to clarify some of the points in #104.

**Comment by erikvansebille** [comment]
Thanks @willirath for bringing to our attention again that installation of Parcels is still suboptimal. We really need to get #104 sorted very soon, and the pointers you provide are very helpful for this. The issue about the `parcels.h` not being found by gcc is an important one, which we will address soon. We'll look into conda forge for sure

**Comment by willirath** [comment]
Turns out that with the `setup.py` from the current master everything works just fine:

Conda environment file `py2_parcels.yml`:

```yml
name: py2_parcels
channels:
  - https://conda.anaconda.org/conda-forge
  - https://repo.continuum.io/pkgs/free
dependencies:
  - python=2.7
  - cachetools>=1.0.0
  - cgen
  - enum34
  - ffmpeg
  - flake8>=2.1.0
  - gcc
  - jupyter
  - matplotlib=2.0.2
  - netcdf4>=1.1.9
  - numpy>=1.9.1
  - progressbar2
  - py>=1.4.27
  - pymbolic
  - python-dateutil
  - scipy>=0.16.0
  - six>=1.10.0
  - xarray>=0.5.1
  - pip:
      - pytest-ipynb
      - pytest>=2.7.0
      - "git+https://github.com/OceanParcels/parcels.git@master"
```

Then (assuming Conda's in your path)

```bash
conda env create --file py2_parcels.yml
source activate py2_parcels
git clone https://github.com/OceanParcels/parcels.git parcels
cd parcels
python parcels/scripts/pull_data.py
cd examples
jupyter notebook
```

And then run the tutorials.
